repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: flake8

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.1.1
    hooks:
    -   id: pylint
        args: [--disable=missing-docstring]
