language: python
python:
  - '3.6'
cache:
  - pip
install:
  - 'pip install pipenv'
  - 'pipenv install --ignore-pipfile'
services:
  - postgres
script:
  - coverage run -m pytest
  - coverage report --omit '/usr/*,/home/travis/virtualenv/*' -m --skip-covered --fail-under=100
  - find . -iname "*.py" | xargs pylint -d "c0111, R0801"
  - flake8
notifications:
  slack:
    secure: YBb8/uqXg4DpIxzsKQfTD8oiFDHf09tM76ymqkPfp02ITUwgY4C0h1xIM1PQgXlOdC+gVOudkrbbwjJQH58fxjM1KNADIHKJ2Q7wg5mjhtPwDxiLeYi2c1U7xPwN8+sMoxM4Nke3r1ZuB/6dsGv16LGawlHLWN0pGL7ZrnBm3aoegKkIUg/WZD6VlsmbtEgIrwbQVS/6TeM+xs3KBx5U45P+d8VAMy++uKmAny/GnJ02vVwffGHCf/GaGKgfFTNadBIvuBUnTpwTsUuwlmr7QVKIVWJUTxMTjA0ZcnjU2zydBzLIOJIhF0xA/GbmLJLJ4UvTFuzO4lpgW8SjWMTIIqMIRpV7r4Ry3NK4oP6RRGkQh7+mVUqie9NXtvZjFCO8XwicitPA8feLCnyZPIYY3w9NmARe4EnPKOwXjGDMg31/FcpeKiJRQcZ9lhsTpCqau6WwnpKec4RPbEuNmIMAc7z0+TgZKbwFe+nxXgwZHhy3Ofq+NYkHjLXx3kSWPQR51Yl5pU9iwvepyrtDsxm59CtxX7wpxo217SD/ArU8rEsID3WtZPbncUh3o6yNnCoUo89nP3Rlx6pOldyLk4LOiQXzkCbPDfznVM9umf3qSywy1iY2qgCnTMjXQgwh3KzJEPHbKJsRIeYiy3rL2Ztc36exKRQJUkGxnMTdI7cYt20=
deploy:
  secret_access_key:
    secure: akGNjGAMXPBToK1v9SOP5er83Jjk3ZIuzUX10k+dKfAFquoSR3bCRYwIE2nD8J1cw8f1oUoD4rtuJZhU4j9Hc+eMgZa6SBsM+BmiiHH2JMvss4cIzFOEt+0DvHvGF55jvHxdJMUq5HAxDFoK1WZ/aYmKaLL2+nOXi9irMuOkVNftJg/Uw5bSsUOcm2cy8/cb6DCnveFq2e/tTSMPttt7UC/kkKkiLF+eveXMHctD8xdwXfBaIJE94MzzN4dSG1ENfCe22dTPg/Qo52dm9Tb7P+o8HwKBwFobn486wjIOXIrh7hsPH+n2ki2uUl/hO1T7U0rlMOSeFFWoWtBqsw6FxK+vgQP2SIDnSVyV/1W12v0z9vD3D2P/TWfp1mWkf0LoU12EHmRn6uHodsfi2EnUs4fzJ6nEyR/zk7Of5+yxZGtLpUOsekte0mQO0W7NXbwx+nQK/eU5nWWByToHk5rPpJeL4uFw6cLxWWmIarsn0UjH1YF62vEtUntxE9olmmXuCDC1+E9LYvcQLFYCYVoheOMIVRLV51zOes3oolQgRC/F9s6lWoy2SdHn6gphiPYvJyl3svKhFTKk9UAhvVatVbPmZzvW3eP/SRkBoCMRLzh08YaQGUnr6L85XlaWyuDnp5zZ8GM9JV9pRZYqh6CcwiVIeTKw4XXcXbPdjT0k6uk=
  access_key_id:
    secure: E6AHpW9KXqowQDdyAfubPXGDYMoDuTK/4iai2uSH2aYgxRJTam7LNg1XvTkt/HUo5/FoIcozHd3Yayicg9xXvqBOq80y46HXK/P96ycsfg+eI4cQRc+tY6U1VCFEVxiexQTh1jbWNbvRrQ+DitPBqTug5kSAo8jsTcMDWmmwEdQvBxEc1u9lI+jiU0GXh4Ckg5Gsnk4XlrCcdvJst7pE0USJdC1gAjDKQ6ZCTjKuJdysgsZg6TlvblEkRAiqy7Wwtmim+SdjlPtm5xzEffKbFEQkGYsqNgvQepGenOm+jOs9QCAqsxx3aXxruk8zPIA3H423Rs8jKTxCyIRQlUYMiAYUaEs6cbiaTVFoW90uVHc11uFsiy+6vPxNIyK/4WdrbJ+GptCYrqWb97JhYQ2nXeaNSQoFtJFbIDExIMTctUCOn+/Z/u1HfFGrsco69XUX/KMNtM0zg+0jSTQCypdJyyviG0soMf0R2Og+p1QzYonfpEbDLqXCrSWqrO/UhVuxTw6qnBuJu3qlwLmtPk3MoNOT+EyR4PhLOpRLmtvmO5PGjUJoSvtdo3rAE5TRzwrY6KFvslnY5CQrF76GAELphETVBKJ0WV029/5L90DcrkUSxwUJlZtIa8FoKd/k3bqosnsI44zJN5P0BOs3bL+WUFVYmla/GgGpAItTZ4W8CDI=
  provider: lambda
  function_name: "satisfaction_lambda"
  region: "ap-southeast-2"
  role: "arn:aws:iam::403741718464:role/Flamily"
  runtime: "python3.6"
  handler_name: "satisfaction_lambda.customer_satisfaction"